# config.yml
local_m3u_path: "playlist_local.m3u"

server:
  host: "0.0.0.0"
  port: 3037

# Optional: override hardware detection by explicitly specifying the profile here
# Leave empty to auto-detect hardware
# Options: hevc_nvenc, h264_nvenc, software_libx264
ffmpeg_profile: ""


