services:
  iptv-streaming-server:
    image: ghcr.io/tw1zt3d2four7/iptv-streaming-server-4-emby:latest
    container_name: iptv-streaming-server
    ports:
      - "3037:3037"   # Maps container port 3037 to host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - ./IPTV-Streaming-Server-4-Emby/config.yml:/app/config.yml:ro   # Mount your config file into the container
      - ./IPTV-Streaming-Server-4-Emby/playlist_local.m3u:/app/playlist_local.m3u:ro  # Mount the playlist
    restart: unless-stopped
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
