services:
  iptv-streaming-server:
    image: ghcr.io/tw1zt3d2four7/iptv-streaming-server-4-emby:dev
    container_name: iptv-streaming-server
    restart: unless-stopped
    ports:
      - "192.168.1.11:3037:3037"
    environment:
      - PUID=1000
      - PGID=1000
      - GIDLIST=1000
      - TZ=America/New_York
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./playlist_local.m3u:/app/playlist_local.m3u:ro
    runtime: nvidia
    devices:
      - "/dev/dri:/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  
