name: Merge Dev into Main (Selective)

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  selective-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add and fetch main branch
        run: |
          git remote add upstream https://github.com/Tw1zT3d2four7/IPTV-Streaming-Server-4-Emby.git
          git fetch upstream main

      - name: Create merge branch
        run: |
          git checkout -b merge-temp upstream/main
          git merge dev --no-commit || true

      - name: Restore protected files from main
        run: |
          git restore --source=upstream/main -- trigger.txt
          git restore --source=upstream/main -- docker-compose.yml
          git restore --source=upstream/main -- .github/workflows/

      - name: Commit merge
        run: |
          git commit -m "Selective merge from dev to main" || echo "No changes to commit"

      - name: Push to main with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Tw1zT3d2four7/IPTV-Streaming-Server-4-Emby.git
          git push origin HEAD:main
