name: Selective Merge Dev to Main

on:
  workflow_dispatch:

jobs:
  selective-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Must have repo scope

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add main branch remote and fetch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream main

      - name: Create temp merge branch from main
        run: |
          git checkout -b merge-temp upstream/main
          git merge dev --no-commit || true  # Merge dev into temp branch

      - name: Restore protected files from main
        run: |
          git restore --source=upstream/main -- trigger.txt
          git restore --source=upstream/main -- docker-compose.yml
          git restore --source=upstream/main -- .github/workflows/

      - name: Commit merge changes
        run: |
          git commit -am "Selective merge dev → main (preserving key files)" || echo "No changes to commit"

      - name: Push merge to main branch
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
