name: Merge Dev into Main (Selective)

on:
  workflow_dispatch:

jobs:
  selective-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: dev
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream remote and fetch main
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream main

      - name: Create merge-temp branch from main
        run: |
          git checkout -b merge-temp upstream/main
          git merge dev --no-commit || true

      - name: Restore protected files from main
        run: |
          git restore --source=upstream/main -- trigger.txt
          git restore --source=upstream/main -- docker-compose.yml
          git restore --source=upstream/main -- .github/workflows/

      - name: Commit merge if changes
        run: |
          git commit -m "Selective merge from dev to main" || echo "No changes to commit"

      - name: Push merge-temp to main
        run: |
          git push origin merge-temp:main
