name: GHCR Login Test

on:
  workflow_dispatch:

jobs:
  ghcr-login-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔧 Set lowercase owner
        run: echo "LOWERCASE_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: ✅ Test login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: ✅ Check login success
        run: |
          echo "Testing docker pull permissions..."
          docker pull ghcr.io/${{ env.LOWERCASE_OWNER }}/nonexistent-image || echo "Login success, image doesn't exist (expected)"
