name: Selective Merge Dev to Main

on:
  workflow_dispatch:

jobs:
  selective-merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout dev branch with your PAT for pushing to main
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.GHCR_PAT }}
          persist-credentials: false  # Important for using your PAT for push

      # Configure Git user
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Prepare to merge from main
      - name: Add main branch remote and fetch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream main

      # Merge dev into a temp branch from main
      - name: Create temp merge branch from main
        run: |
          git checkout -b merge-temp upstream/main
          git merge dev --no-commit || true

      # Restore protected files from main
      - name: Restore protected files from main
        run: |
          git restore --source=upstream/main -- trigger.txt
          git restore --source=upstream/main -- docker-compose.yml
          git restore --source=upstream/main -- .github/workflows/

      # Commit the merge (if there are changes)
      - name: Commit merge changes
        run: |
          git commit -m "Selective merge dev → main (preserving key files)" || echo "No changes to commit"

      # Push the merge to main using your PAT
      - name: Push merge to main branch
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main

      # Login to GitHub Container Registry (GHCR) using GITHUB_TOKEN (works with 2FA)
      - name: Login to GitHub Container Registry
        if: false  # Disabled by default, set to 'true' or remove this line if you want to use it
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT}}
